# site settings
title: 
subtitle: 
email: jgphilip@gmail.com
description: AN ANDROID DEVELOPER<br /> FOOTBALL FANATIC
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Somewhere Road
city: Toronto
state: ON
zip_code: 
country: Canada
phone: -NA-

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/jgphilip
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com/jgphilip
linkedin_url: https://www.linkedin.com/in/jeevanphilip
pinterest_url:
slack_url:
twitter_url: https://twitter.com/jgphilip

# build settings
markdown: kramdown

sass:
  style: compressed

theme: jekyll-theme-cayman
